name: ML CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirments.txt

      - name: Build Docker image
        run: docker build -t docker_lr .

      - name: Run Docker container
        run: docker run docker_lr